### ISSUE TITLE
Can i use it in Unity3d?

### ISSUE THREAD

**Issue by leewalf** [Fishezzz/Project-DMX-Light-Controller-v2.0#5]
As a developer of Unity3d, I only have some understanding of the basic syntax of c#, but I am not very familiar with.net development. Could you please tell me how to reference your library to communicate with DMX lamps through c#?

**Comment by Fishezzz** [comment]
Sorry for the late response, I didn't think people would be interested in this repo, since this is a repo for a school project from 1,5 years ago.
This is more an app than a library so I don't know how well you will be able to use this for what you want to do. But I'll try to give some info that is useful for what you want to know/do. But you can use certain parts as a library (`Logger` is build to be such thing, and `DMX` might also work when used like that).

----

There are 4 projects: an installer, a logger, a project with all the device classes and UI tabs and the main project/the app.
1. [DmxInstaller](https://github.com/Fishezzz/Project-DMX-Light-Controller-v2.0/tree/master/DmxInstaller) : The installer for the app. Made in Visual Studio 2017 and now incompatible with Visual Studio 2019. But I'll try and make a new installer project compatible with VS2019.
2. [Logger](https://github.com/Fishezzz/Project-DMX-Light-Controller-v2.0/tree/master/Logger) : Just a simple logger class,, a Singleton, that you can use in this (or other) project. It writes to a file when you call `logger.Log()`, `logger.Warn()` or `logger.Error()`. You can also dump an Error in it and it will log as an 'Error' with the message + StackTrace.
3. [DMX](https://github.com/Fishezzz/Project-DMX-Light-Controller-v2.0/tree/master/DMX) : This project contains [classes](https://github.com/Fishezzz/Project-DMX-Light-Controller-v2.0/tree/master/DMX/Entities) and [UI tabs](https://github.com/Fishezzz/Project-DMX-Light-Controller-v2.0/tree/master/DMX/Tabs) for each type DMX device used. (the devices that were present in the class room) The class also describes functions to modify the values of specific DMX channels when the user changes something in the UI Tab for that device. Most of the math and logic for these functions al everything related to the DMX channels, etc.. is based of the [datasheets](https://github.com/Fishezzz/Project-DMX-Light-Controller-v2.0/tree/master/DMX/Resources/Datasheets) of the DMX devices.
4. [Project DMX 2.0](https://github.com/Fishezzz/Project-DMX-Light-Controller-v2.0/tree/master/Project%20DMX%202.0) : The main application that the user interacts with and controls the DMX devices. It sends the actual bytes to control the devices. (via a USB to DMX converter/connector, that was provided by my teacher) ([a USB to DMX DIY guide](https://stevenbreuls.com/2013/05/diy-usb-dmx-dongle-interface-for-under-10/))

A `SerialPort` is used to transmit the bytes, via a COM-port, to USB. So there is no extra library used, just [`System.IO.Ports`](https://docs.microsoft.com/en-us/dotnet/api/system.io.ports) for the [SerialPort](https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport).

If I would guess, I think you would only need the last part, the SerialPort, for the DMX communication and control your lamps (in a rudimentary way).

_Edit: The installer works but you need to install the "[Microsoft Visual Studio Installer Projects](https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects)" extension first._
